


const Types = {
    SET_ME: 'SET_ME',
    ME_ERROR: 'ME_ERROR',
    SET_USERS: 'SET_USERS',
    USERS_ERROR: 'USERS_ERROR',
    SET_ATTACHMENTS: 'SET_ATTACHMENTS',
    ATTACHMENTS_ERROR: 'ATTACHMENTS_ERROR',
}


export default Types